# Generated by Django 2.2.7 on 2020-06-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
    ]
