# Generated by Django 2.1.15 on 2020-06-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecomment',
            old_name='title',
            new_name='content',
        ),
    ]
